
# This file is automatically generated, you probably don't want to edit this

addnewvarOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "addnewvarOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            factor = NULL, ...) {

            super$initialize(
                package="creavarj",
                name="addnewvar",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                required=TRUE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..factor <- jmvcore::OptionVariable$new(
                "factor",
                factor,
                rejectUnusedLevels=TRUE,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..newvarOV <- jmvcore::OptionOutput$new(
                "newvarOV")

            self$.addOption(private$..dep)
            self$.addOption(private$..factor)
            self$.addOption(private$..newvarOV)
        }),
    active = list(
        dep = function() private$..dep$value,
        factor = function() private$..factor$value,
        newvarOV = function() private$..newvarOV$value),
    private = list(
        ..dep = NA,
        ..factor = NA,
        ..newvarOV = NA)
)

addnewvarResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "addnewvarResults",
    inherit = jmvcore::Group,
    active = list(
        newvarOV = function() private$.items[["newvarOV"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Add NewVar")
            self$add(jmvcore::Output$new(
                options=options,
                name="newvarOV",
                title="Add NewVar",
                varTitle="NewVar",
                varDescription="NewVar added with the creavarj module",
                measureType="continuous",
                clearWith=list(
                    "dep",
                    "factor")))}))

addnewvarBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "addnewvarBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "creavarj",
                name = "addnewvar",
                version = c(0,0,1),
                options = options,
                results = addnewvarResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Add NewVar
#'
#' 
#' @param data the data as a data frame
#' @param dep the dependent variable from \code{data}, variable must be
#'   numeric
#' @param factor the explanatory factors in \code{data} (not necessary when
#'   providing a formula, see examples)
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$newvarOV} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' @export
addnewvar <- function(
    data,
    dep,
    factor = NULL) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("addnewvar requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(factor)) factor <- jmvcore::resolveQuo(jmvcore::enquo(factor))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(factor), factor, NULL))

    for (v in factor) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- addnewvarOptions$new(
        dep = dep,
        factor = factor)

    analysis <- addnewvarClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

